AMQP_URI: pyamqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:password}@${RABBITMQ_HOST:localhost}
WEB_SERVER_ADDRESS: "0.0.0.0:8000"
rpc_exchange: "nameko-rpc"
max_workers: 10
parent_calls_tracked: 10

LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  root:
    level: ${LOG_LEVEL:DEBUG}
    handlers: [console]
